title: Ordinary Evidence
email: info@ordinaryevidence.org
description: Ordinary claims require ordinary evidence
baseurl: ""
url: "https://ordinaryevidence.org"
github_username: ordinaryevidence

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
